FROM golang:1.19 AS builder

WORKDIR /app

COPY . .

RUN go mod download
RUN go mod tidy
RUN go build -o expense-service main.go

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/expense-service /app/

RUN apt-get update && apt-get install -y --no-install-recommends libc6 libc6-dev

EXPOSE 8081

CMD ["./expense-service"]
